#!/bin/bash
# PRIMUS 1.8.0
# Generated by dx-app-wizard.
#
# Your job's input variables (if any) will be loaded as environment
# variables before this script runs.  Any array inputs will be loaded
# as bash arrays.
#
# Any code outside of main() (or any entry point you may add) is
# ALWAYS executed, followed by running the entry point itself.
#
# See https://wiki.dnanexus.com/Developer-Portal for tutorials on how
# to modify this file.

# The following line causes bash to exit at any point if there is any error
# and to output each line as it is executed -- useful for debugging
set -e -x -o pipefail

dx-download-all-inputs
echo "IBD estimates: $IBD_estimates_path"
echo "degree_of_relationship_cutoff: '$degree_of_relationship_cutoff'"

mkdir -p ~/out/results/

CMD_OPTIONS=`head $PR_commands_path`

echo "run_reconstruction.pl $CMD_OPTIONS --MITO_FILE $mito_file_path --Y_FILE $y_file_path --FILE $IBD_estimates_path --age_file $age_file_path --affection_file $affection_file_path --sex_file $sex_file_path"

run_reconstruction.pl $CMD_OPTIONS --FILE $IBD_estimates_path --age_file $age_file_path --affection_file $affection_file_path --sex_file $sex_file_path --output_dir ~/out/results

rm ~/out/results/*.cranefoot.fam
rm ~/out/results/*.config

cd ~/out/results/
lines=$(ls | wc -l) 

echo "lines: $lines"

if [ "$lines" -gt "24" ]
then
    echo "lines2: $lines"
    ls | grep -P 'network\d+_\d{2,}\.('fam'|'ps')' > temp
    tar -cvz -T temp -f possible_pedigrees_10_and_over.tgz
    for file in $(ls | grep -P 'network\d+_\d{2,}\.('fam'|'ps')')
    do
        rm $file
    done
    rm temp
fi


#run_PRIMUS.pl -p "$IBD_estimates_path" --degree_rel_cutoff $degree_of_relationship_cutoff -o ~/out/results --cluster

dx-upload-all-outputs --parallel

